version: '3'

services:
  vaultwarden:
    image: vaultwarden/server: latest
    container_name: vaultwarden
    env_file:
      - .env
    restart: always
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=true
      - SMTP_PORT=587
      - SMTP_SSL=true
    volumes:
      - ./vaultdata:/data

  caddy:
    image: caddy:2
    container_name: caddy
    env_file:
      - .env
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-config:/config
      - ./caddy-data:/data
    environment:
      - LOG_FILE=/data/access.log
